[AVATARS]
user = "https://raw.githubusercontent.com/namigabbasov/sundevilchat/main/static/user_icon.png"
assistant = "https://raw.githubusercontent.com/namigabbasov/sundevilchat/main/static/llm_icon.png"

[ROLES]
user = "user"
assistant = "assistant"

[main]
title = "Sun Devil GPT"
logo = "![Kingbot](./app/static/sundevil.png)"

[side]
title = "[![ASU Library](./app/static/asu_library_logo.png)](https://lib.asu.edu/)"
intro = "SunDevil Library Chat is a workshop demonstration of an AI-powered assistant designed to help users with general questions about Arizona State University (ASU) Library services. This tool is not an official ASU Library service and does not replace librarians or library staff."
policylink = "https://lib.asu.edu/"
policylabel = "See SunDevil Library Chat Policy"

[button1]
label = "ASU Library Hours"
content = "How can I find ASU Library hours?"
chip = "SC: Hours"

[button2]
label = "Get Research Help"
content = "Can you help me get started with research at ASU Library?"
chip = "SC: ResearchStart"

[button3]
label = "Find Library Services"
content = "What services does ASU Library offer to students and faculty?"
chip = "SC: BorrowLaptop"